name: Gears/pdf test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: update qq
      run: sudo apt-get update -qq

    - name: install libreoffice
      run: sudo apt-get install -y libreoffice-writer

    - name: install unoconv
      run: sudo apt-get install -y unoconv

    - name: Install dependencies
      run: composer install

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: ./vendor/bin/robo test
